version: "3.3"
services:
  db:
    image: postgres:alpine3.17
    hostname: postgre
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

  event-service-rest:
    image: rest:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  db:
    driver: local
