version: "3.3"
services:
  db:
    image: postgres:alpine3.17
    hostname: postgre
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

  event-service-rest:
    image: rest:latest
    depends_on:
      - db
      - auction
      - discovery-service

  auction:
    image: auction:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
      - discovery-service

  discovery-service:
    image: discovery-service:latest
    ports:
      - '8761:8761'
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:v2.37.6
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=passwd
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  db:
    driver: local
  prometheus-data:
    driver: local
  grafana_data:
    driver: local
  auction-data:
    driver: local
  discovery-service:
    driver: local
